config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  get "search" => "items#search"

  namespace :admin do
    get "orders/index/:customer_id" => "orders#index", as: "order_index"
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    resources :ordering_details, only: [:update]
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  namespace :admin do
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
  end

  namespace :admin do
    root to: "homes#top"
  end

  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  scope module: :public do
    post "orders/confirm" => "orders#confirm", as: "confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only: [:new, :index, :show, :create]
  end

  scope module: :public do
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end

  get "customers/my_page" => "public/customers#show", as: "my_page"
  get "customers/information/edit" => "public/customers#edit", as: "information_edit"
  patch "customers/information" => "public/customers#update", as: "information_update"
  get "customers/unsubcribe" => "public/customers#unsubcribe"
  patch "customers/withdraw" => "public/customers#withdraw"

  scope module: :public do
    resources :items, only: [:index, :show]
  end

  get "homes/about" => "public/homes#about", as: "about"

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    #sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :ordering_details, dependent: :destroy
  belongs_to :genre

  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
  ## 消費税を求めるメソッド
  def add_tax_price
    (self.price * 1.10).floor
  end
  
  def search
    if params[:name].present?
      @items = Item.where("name LIKE ?", "%#{params[:name]}%")
    else
      @items = Item.none
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  layout "admin/layouts/application"  # layoutを宣言

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @is_active = @item.is_active ? "販売中" : "販売停止中"
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private
    def item_params
      params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active)
    end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="page_title mb-3 pl-3 pr-3">
        商品編集
</div>
<div class="error-message">
    <% if @item.errors.any? %>
        <%= @item.errors.count %>件のエラーメッセージが発生しました
          <ul>
            <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
            <% end %>
          </ul>
    <% end %>
</div>

<div style="text-align: center" class="w-50% mt-3">
    <div class="form-group d-inline-block" style="text-align: left">

<%= form_with model:@item, url: admin_item_path(@item), method: :patch, local: true do |f| %>
        <div class="form-group" >
            <%= f.label :image, "商品画像　　　　" %>
            <%= f.file_field :image,  accept: "image/*" %> 
        </div>

        <div class="form-group" >
            <%= f.label :name, "商品名　　　　　" %>
            <%= f.text_field :name, :size=>"30" %> 
        </div>

        <div class="form-group" >
            <%= f.label :intruduvtion, "商品説明　　　　", class: "item-introduction-label" %>
            <%= f.text_area :introduction, size: "30x5" %> 
        </div>

        <div class="form-group" >
            <%= f.label :genre_id, "ジャンル　　　　" %>
            <%= f.select :genre_id, @genres.map{ |genre| [genre.name, genre.id] }, include_blank: '--選択してください--　　　　　' %>
        </div>
        
        <div class="form-group" >
            <%= f.label :price, "税抜価格　　　　" %>
            <%= f.text_field :price, :size=>"31" %> 円
        </div>
    
        <div class="form-group" >
            <%= f.label :is_active, "販売ステータス　" %>
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;", class: "mr-3"} %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>
        </div>

</div>
        <div style="text-align: center">
            <%= f.submit '　　変更を保存　　',class: "btn btn-success mb-4" %>
        </div>

<% end %>

    

app/views/admin/items/index.html.erb
<div class="ml-2">
    <div class="page_title pl-3 pr-3">
        商品一覧
    </div>
</div>

    <div class="new_item_icon">
        <%= link_to new_admin_item_path do %>
            <i class="fas fa-plus-circle fa-2x" style="color: gainsboro;"></i>
        <% end %>
    </div>
</div>

<div class="container m-10">
<table class="table" border="2" rules="rows" frame="hsides" bordercolor="silver">
    <thead bgcolor="#DDDDDD">
     <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
     </tr>
    </thead>
    
    <tbody>
     <% @items.each do |item| %>
     <tr>
        <td>
            <%= item.id %>
        </td>
        <td>
         <%= link_to admin_item_path(item.id) do %>
            <%= item.name %>
         <% end %>
        </td>
        <td>
            <%= item.price.to_s(:delimited) %>
        </td>
        <td>
            <%= item.genre.name %>
        </td>
        
        <% if item.is_active == true %>
            <td class="now_on_sale">販売中</td>
        <% else %>
            <td class="sold_out">販売停止中</td>
    　　<% end %>
    　　
     </tr>
     <% end %>
    </tbody>
</table>
</div>

            <%= paginate @items, theme: 'bootstrap-5' %>

app/views/admin/items/new.html.erb
<div class="page_title mb-3 pl-3 pr-3">
    商品新規登録
</div>
    <% if @item.errors.any? %>
        <%= @item.errors.count %>件のエラーメッセージが発生しました
          <ul>
            <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
            <% end %>
          </ul>
    <% end %>
</div>

<div style="text-align: center" class="w-50% mt-3">
    <div class="form-group d-inline-block" style="text-align: left">

        <%= form_with model:@item, url: admin_items_path(@item), method: :post, local: true do |f| %>
        <div class="form-group">
            <%= f.label :image, "商品画像　　　　" %>
            <%= f.file_field :image, accept: "image/*" %> 
        </div>
        <div class="form-group">
            <%= f.label :name, "商品名　　　　　" %>
            <%= f.text_field :name, :size=>"30" %> 
        </div>    
        <div class="form-group">
            <%= f.label :intruduction, "商品説明　　　　", class: "item-introduction-label" %>
            <%= f.text_area :introduction, size: "30x5" %> 
        </div>
        <div class="form-group">
            <%= f.label :genre_id, "ジャンル　　　　" %>
            <%= f.select :genre_id, @genres.map{ |genre| [genre.name, genre.id] }, include_blank: '--選択してください--　　　　　　' %>
        </div>
        <div class="form-group">
            <%= f.label :price, "税抜価格　　　　" %>
            <%= f.text_field :price, :size=>"31" %> 円
        </div>
        <div class="form-group m-0">
            <%= f.label :is_active, "販売ステータス　" %>
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;", class: "mr-3"} %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>
        </div>
    </div>
</div>
    <div style="text-align: center">
            <%= f.submit '　　新規登録　　',class: "btn btn-success mb-4" %>
    </div>
        <% end %>
    

app/views/admin/items/show.html.erb
<div class="page_title mb-5 pl-3 pr-3">
        商品詳細
</div>


<div class="container d-flex">
        <div class="col-4 mt-10">
            <% if @item.image.attached? %>
                <%= image_tag @item.image, size: "300x200" %>
            <% else %>
                <%= image_tag 'sample_image.jpeg', size: "300x200" %>
            <% end %>
        </div>
        <div class="col-8">
            <div>
                <p class="fw-bolder">商品名　　　　　 　 <%= @item.name %></p>
            </div>
            <div class="">
                <p class="fw-bolder">商品説明　　　　 　 <%= @item.introduction %></p>
                
            </div>
            <div class="">
                <p>ジャンル　　　　 　 <%= @item.genre.name %></p>
            </div>
            <div class="d-flex">
                <p class="mr-5 fw-bolder">税込価格</br>（税抜価格）</p>
                <p class="ml-2 fw-bolder"><%= @item.add_tax_price.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>)円</p>
                
            </div>
            <div class="d-flex">
                <p class="mr-5 fw-bolder">販売ステータス</p>
                <% if @item.is_active == true %>
                    <p class="now_on_sale"><%= "販売中" %></p>
                <% else %>
                    <p class="sold_out"><%=  "販売停止中" %></p>
                <% end %>
            </div>
        </div>
</div>

<div style="text-align: center">
                <%= link_to '編集する', edit_admin_item_path(@item.id),  class: "btn btn-success pl-4 pr-4 mt-2" %>
</div>