config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  get "search" => "items#search"

  namespace :admin do
    get "orders/index/:customer_id" => "orders#index", as: "order_index"
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    resources :ordering_details, only: [:update]
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  namespace :admin do
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
  end

  namespace :admin do
    root to: "homes#top"
  end

  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  scope module: :public do
    post "orders/confirm" => "orders#confirm", as: "confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only: [:new, :index, :show, :create]
  end

  scope module: :public do
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end

  get "customers/my_page" => "public/customers#show", as: "my_page"
  get "customers/information/edit" => "public/customers#edit", as: "information_edit"
  patch "customers/information" => "public/customers#update", as: "information_update"
  get "customers/unsubcribe" => "public/customers#unsubcribe"
  patch "customers/withdraw" => "public/customers#withdraw"

  scope module: :public do
    resources :items, only: [:index, :show]
  end

  get "homes/about" => "public/homes#about", as: "about"

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    #sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  layout "admin/layouts/application"  # layoutを宣言

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    if customer.update(customer_params)
      redirect_to admin_customer_path(customer.id)
    else
      render :edit
    end
  end

private
  def customer_params
    params.require(:customer).permit(:firsr_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="page_title mb-3 pl-3 pr-3">
  <%= @customer.first_name + @customer.last_name %>の会員情報編集
</div>



<div class="container m-3">
        <div class="row m-3">
            <div class="font-weight-bold">会員ID　　　　　　    </div>
            <%= @customer.id %>
        </div>
</div>

<%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>

  <div class="form-group">
    <%= f.label :first_name, "氏名　　　　　　　", class: "font-weight-bold ml-5" %>
    <%= f.text_field :first_name, autocomplete: "first_name" %>
    <%= f.text_field :last_name, autocomplete: "last_name" %>
  </div>
  
  <div class="form-group">
    <%= f.label :first_name_kana, "フリガナ　　　　　", class: "font-weight-bold ml-5" %>
    <%= f.text_field :first_name_kana, autocomplete: "first_name_kana" %>
    <%= f.text_field :last_name_kana, autocomplete: "last_name_kana" %>
  </div>
  
  <div class="form-group">
    <%= f.label :postal_code, "郵便番号　　　　　", class: "font-weight-bold ml-5" %>
    <%= f.number_field :postal_code, autocomplete: "postal_code" %>
  </div>
  
  <div class="form-group">
    <%= f.label :address, "住所　　　　　　　", class: "font-weight-bold ml-5" %>
    <%= f.text_field :address,autocomplete: "address" %>
  </div>
  
  <div class="form-group">
    <%= f.label :telephone_number, "電話番号　　　　　", class: "font-weight-bold ml-5" %>
    <%= f.number_field :telephone_number, autocomplete: "telephone_number" %>
  </div>

  <div class="form-group">
    <%= f.label :email, "メールアドレス　　", class: "font-weight-bold ml-5" %>
    <%= f.email_field :email, autocomplete: "email" %>
  </div>
  
  <div class="form-group">
        <%= f.label :is_active, "会員ステータス　　", class: "font-weight-bold ml-5" %>
        <%= f.radio_button :is_deleted, :false %>
        <%= f.label :is_deleted, "有効", {value: :false, style: "display: inline-block;", class: "pr-3"} %>
        <%= f.radio_button :is_deleted, :true %>
        <%= f.label :is_deleted, "退会", {value: :true, style: "display: inline-block;"} %>
  </div>


  <div style="text-align: left"  class="customer_show_btn">
    <%= f.submit '　変更を保存　',class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/customers/index.html.erb
<div class="page_title mb-3 pl-3 pr-3">
    会員一覧
</div>

<div class="container m-10">
<table class="table table-customers" border="2" rules="rows" frame="hsides" bordercolor="silver">
    <thead bgcolor="#DDDDDD">
        <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
        </tr>
    </thead>
    
    <tbody>
     <% @customers.each do |customer| %>
     <tr>
        <td>
            <%= customer.id %>
        </td>
        <td>
         <%= link_to admin_customer_path(customer.id) do %>
            <%= customer.first_name + customer.last_name %>
         <% end %>
        </td>
        <td>
            <%= customer.email %>
        </td>
        
        <% if customer.is_deleted == false %>
            <td class="validity">有効</td>
        <% else %>
            <td class="withdraw">退会</td>
    　　<% end %>
    　　
     </tr>
     
     <% end %>
    </tbody>
</table>

    <%= paginate @customers, theme: 'bootstrap-5' %>

app/views/admin/customers/show.html.erb
<div class="page_title mb-4 pl-3 pr-3">
    <%= @customer.first_name + @customer.last_name %>さんの会員詳細
</div>

<div class="container ml-5">
        <div class="row m-3">
            <div class="font-weight-bold">会員ID　　　　　　</div>
            <%= @customer.id %>
        </div>
        <div class="row m-3">
            <div class="font-weight-bold">氏名　　　　　　　</div>
            <%= @customer.first_name + @customer.last_name %>
        </div>
        <div class="row m-3">
            <div class="font-weight-bold">フリガナ　　　　　</div>
                <%= @customer.first_name_kana + @customer.last_name_kana %>
        </div>
        <div class="row m-3">
            <div class="font-weight-bold">郵便番号　　　　　</div>
                <%= @customer.postal_code %>
        </div>
        <div class="row m-3">
            <div class="font-weight-bold">住所　　　　　　　</div>
                <%= @customer.address %>
        </div>
        <div class="row m-3">
            <div class="font-weight-bold">電話番号　　　　　</div>
                <%= @customer.telephone_number %>
        </div>
        <div class="row m-3">
            <div class="font-weight-bold">メールアドレス　　</div>
                <%= @customer.email %>
        </div>
        <div class="row m-3">
            <div class="font-weight-bold">会員ステータス　　</div>
                <% if @customer.is_deleted == false %>
                <div class="validity">
                    <td>有効</td>
                </div>
                <% else %>
                <div class="withdraw">
                    <td >退会</td>
                </div>
    　　          <% end %>
        </div>
</div>

<div style="text-align: left"  class="customer_show_btn">
                <%= link_to '編集する', edit_admin_customer_path(@customer.id),  class: "btn btn-success mr-5" %>
            
                <%= link_to '注文履歴一覧を見る', admin_order_index_path(@customer.id),  class: "btn btn-primary ml-3" %>
</div>