config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  get "search" => "items#search"

  namespace :admin do
    get "orders/index/:customer_id" => "orders#index", as: "order_index"
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    resources :ordering_details, only: [:update]
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  namespace :admin do
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
  end

  namespace :admin do
    root to: "homes#top"
  end

  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  scope module: :public do
    post "orders/confirm" => "orders#confirm", as: "confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only: [:new, :index, :show, :create]
  end

  scope module: :public do
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end

  get "customers/my_page" => "public/customers#show", as: "my_page"
  get "customers/information/edit" => "public/customers#edit", as: "information_edit"
  patch "customers/information" => "public/customers#update", as: "information_update"
  get "customers/unsubcribe" => "public/customers#unsubcribe"
  patch "customers/withdraw" => "public/customers#withdraw"

  scope module: :public do
    resources :items, only: [:index, :show]
  end

  get "homes/about" => "public/homes#about", as: "about"

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    #sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :ordering_details, dependent: :destroy

  validates :delivery_postal_code, presence: true
  validates :delivery_address, presence: true
  validates :delivery_name, presence: true
  validates :payment, presence: true

  enum payment: { credit: 0, bank: 1 }
  enum order_status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  layout "admin/layouts/application"  # layoutを宣言

  def show
    @order = Order.find(params[:id])
    @customer = @order.customer_id
    @ordering_details = @order.ordering_details
  end

  def index
    @customer = Customer.find(params[:customer_id])
    @orders = @customer.orders.page(params[:page]).order("created_at DESC")
  end

  def update
    @order = Order.find(params[:id])
    @ordering_details = @order.ordering_details
    @order.update(order_params)

    @ordering_details.each do |ordering_detail|
      if @order.order_status == "payment_confirmation"
        ordering_detail.update(production_status: "production_pending")
      end
    end


    redirect_to admin_order_path(@order)
  end

  private
    def order_params
      params.require(:order).permit(:payment, :delivery_postal_code, :delivery_address, :delivery_name, :postage, :total_payment, :customer_id, :order_status)
    end

    def ordering_detail_params
      params.require(:ordering_detail).permit(:order_id, :item_id, :price, :amount, :production_status)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="ml-3">
    <div class="page_title mb-4 pl-3 pr-3">
        <%= @customer.first_name + @customer.last_name %>さんの注文履歴
    </div>
</div>

<div class="container ml-10">
<table class="table" border="2" rules="rows" frame="hsides" bordercolor="silver">
    <thead bgcolor="#DDDDDD">
        <tr>
            <th>購入日時</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
        </tr>
    </thead>
    
    <tbody>
        <% @orders.each do |order| %>
            <tr>
                <td>
                    <%= link_to admin_order_path(order.id) do %>
                        <%= l order.created_at %>
                    <% end %>
                </td>
                <td><%= order.ordering_details.sum(:amount) %></td>
                <td><%= order.order_status_i18n %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= paginate  @orders, theme: 'bootstrap-5' %>
</div>

app/views/admin/orders/show.html.erb
<div class="page_title pl-3 pr-3">
        注文履歴詳細
</div>

<div class="container m-3">
    <div class="row m-3">
        <div class="font-weight-bold">　　購入者　　　　　　</div>
        <%= link_to admin_order_index_path(@order.customer.id) do %>
        <%= @order.customer.first_name + @order.customer.last_name %>
        <% end %>
    </div>
    <div class="row m-3">
        <div class="font-weight-bold">　　注文日　　　　　　</div>
        <%= l @order.created_at %>
    </div>
    <div class="row m-3">
       <div class="font-weight-bold">　　配送先　　　　　　</div>
        <%= @order.delivery_address %>
    </div>
    <div class="row m-3">
        <div class="font-weight-bold">　　支払方法　　　　　</div>
        <%= @order.payment_i18n %>
    </div>
     <div class="row m-3">
        <div class="font-weight-bold">　　注文ステータス　　</div>
        <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch, local: true do |f| %>
            <%= f.select :order_status, Order.order_statuses_i18n.invert %>
            <%= f.submit '更新', class: "btn btn-success ml-3" %>
        <% end %>
    </div>
    
   <table class="table total-table ml-5" border="2" rules="rows" frame="hsides" bordercolor="silver">
    <thead bgcolor="#DDDDDD">
        <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
        </tr>
    </thead>
            <% @ordering_details.each do |ordering_detail| %>
    <tbody>

        <tr>
            <td><%= ordering_detail.item.name %></td>
            <td><%= (ordering_detail.price * 1.1).floor.to_s(:delimited) %></td>
            <td><%= ordering_detail.amount %></td>
            <td><%= (ordering_detail.price * 1.1 * ordering_detail.amount).floor.to_s(:delimited) %></td>
            <td>
                <%= form_with model: ordering_detail, url: admin_ordering_detail_path(ordering_detail), method: :patch, local: true do |f| %>
                    <%= f.hidden_field :order_id, value: @order.id %>
                    <%= f.hidden_field :item_id, value: ordering_detail.item_id %>
                    <%= f.hidden_field :price, value: ordering_detail.price %>
                    <%= f.hidden_field :amount, value: ordering_detail.amount %>
                    <%= f.select :production_status, OrderingDetail.production_statuses_i18n.invert %>
                    <%= f.submit '更新', class:"btn btn-success ml-3" %>
                <% end %>
            </td>
        </tr>
        
    </tbody>
    <% end %>
    </table>
    <div class="absolute_parent">
    <div class="absolute">
        <table>
            <tr>
                <th class="font-big">商品合計</th>
                <td class="font-big"><%= @order.total_payment.to_s(:delimited) %>円</td>
            </tr>
            <tr>
                <th class="font-big">送料</th>
                <td class="font-big"><%= @order.postage.to_s(:delimited) %>円</td>
            </tr>
            <tr>
                <th class="font-big" width="140px">請求金額合計</th>
                <td class="font-big"><b><%= (@order.total_payment + @order.postage).to_s(:delimited) %>円</b></td>
            </tr>
        </table>
    </div>
</div>