config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"

  get "search" => "items#search"

  namespace :admin do
    get "orders/index/:customer_id" => "orders#index", as: "order_index"
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    resources :ordering_details, only: [:update]
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  namespace :admin do
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
  end

  namespace :admin do
    root to: "homes#top"
  end

  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  scope module: :public do
    post "orders/confirm" => "orders#confirm", as: "confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only: [:new, :index, :show, :create]
  end

  scope module: :public do
    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end

  get "customers/my_page" => "public/customers#show", as: "my_page"
  get "customers/information/edit" => "public/customers#edit", as: "information_edit"
  patch "customers/information" => "public/customers#update", as: "information_update"
  get "customers/unsubcribe" => "public/customers#unsubcribe"
  patch "customers/withdraw" => "public/customers#withdraw"

  scope module: :public do
    resources :items, only: [:index, :show]
  end

  get "homes/about" => "public/homes#about", as: "about"

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    #sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :customer_id, presence: true
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def address_display
    "〒" + postal_code + " " + address + " " + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true
  ## 小計を求めるメソッド
  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :ordering_details, dependent: :destroy
  belongs_to :genre

  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
  ## 消費税を求めるメソッド
  def add_tax_price
    (self.price * 1.10).floor
  end
  
  def search
    if params[:name].present?
      @items = Item.where("name LIKE ?", "%#{params[:name]}%")
    else
      @items = Item.none
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :ordering_details, dependent: :destroy

  validates :delivery_postal_code, presence: true
  validates :delivery_address, presence: true
  validates :delivery_name, presence: true
  validates :payment, presence: true

  enum payment: { credit: 0, bank: 1 }
  enum order_status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }
end

app/models/ordering_detail.rb
class OrderingDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum production_status: { start_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  layout "admin/layouts/application"  # layoutを宣言

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    if @genre.save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

 private
   def genre_params
     params.require(:genre).permit(:name)
   end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  layout "admin/layouts/application"  # layoutを宣言

  def top
    @orders = Order.page(params[:page]).order("created_at DESC")
    @cart_items = CartItem.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  layout "admin/layouts/application"  # layoutを宣言

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @genres = Genre.all
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @is_active = @item.is_active ? "販売中" : "販売停止中"
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @genres = Genre.all
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private
    def item_params
      params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="border-bottom border-dark">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand border border-dark mt-3" href="/admin"><%= image_tag 'logo.png' %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
            <li class="nav-item border border-gray rounded mr-3">
              <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item border border-gray rounded mr-3">
              <%= link_to "会員一覧",admin_customers_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item border border-gray rounded mr-3">
              <%= link_to "注文履歴一覧", admin_root_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item border border-gray rounded  mr-3" >
              <%= link_to 'ジャンル一覧', admin_genres_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item border border-gray rounded">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item border border-gray rounded  mr-3" >
              <%= link_to 'About', about_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item border border-gray rounded  mr-3" >
              <%= link_to '商品一覧', admin_items_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item border border-gray rounded mr-3">
              <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item border border-gray rounded">
              <%= link_to "ログイン", new_admin_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
            
          </div>
        </div>
      </nav>
      <div class="search_form mb-2 float-right">
              <%= form_with url: search_path, method: :get, local: true do |f| %>
                <%= f.text_field :name %>
                <%= f.submit :search %>
              <% end %>
      </div>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-white border-top border-dark pt-5 pb-4" >
      <div class="container">
        
      </div>
    </footer>
    
</html>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>